language: java
jdk:
  - openjdk11

branches:
  only:
    - master

#Travis CI server's home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradle clean build"

#CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - byol0425@naver.com
